---
- name: SSH Server Hardening
  gather_facts: yes
  hosts: webserver
 
##################### Defined  Variables ####################################

  vars:

    os_rest:
      - servera
      - serverb
      - serverc
      - serverd
    os_Ubuntu:
      - servere
    os_sa:
      - servera
    os_sb:
      - serverb
    os_sc:
      - serverc
    os_sd:
      - serverd
    os_se:
      - servere
    ip_servera:
      - 10.0.0.2
    ip_serverb:
      - 10.0.0.3
    ip_serverc:
      - 10.0.0.4
    ip_serverd:
      - 10.0.0.5
    ip_servere:
      - 192.168.181.138
    unnecessary_services:
      - postfix
    unnecessary_software:
      - tcpdump
      - nmap-ncat
      - wpa_supplicant

####################  Ansible will perform following tasks  #######################

  tasks:

########################  Patch software  #########################################

    - name: Perform full patching
      package:
        name: '*'
        state: latest 

######################  Internal & Public zone securing  #########################

    - name: Add SSH port to internal zone
      firewalld:
        zone: internal
        service: ssh
        state: enabled
        immediate: yes
        permanent: yes

    - name: Add permitted networks to internal zone
      firewalld:
        zone: internal
        source: "{{ item }}"
        state: enabled
        immediate: yes
        permanent: yes
      with_items: "{{ ip_servera }}"
      when: ansible_distribution in os_sa

    - name: Add permitted networks to internal zone
      firewalld:
        zone: internal
        source: "{{ item }}"
        state: enabled
        immediate: yes
        permanent: yes
      with_items: "{{ ip_serverb }}"
      when: ansible_distribution in os_sb

    - name: Add permitted networks to internal zone
      firewalld:
        zone: internal
        source: "{{ item }}"
        state: enabled
        immediate: yes
        permanent: yes
      with_items: "{{ ip_serverc }}"
      when: ansible_distribution in os_sc

    - name: Add permitted networks to internal zone
      firewalld:
        zone: internal
        source: "{{ item }}"
        state: enabled
        immediate: yes
        permanent: yes
      with_items: "{{ ip_serverd }}"
      when: ansible_distribution in os_sd

    - name: Add permitted networks to internal zone
      firewalld:
        zone: internal
        source: "{{ item }}"
        state: enabled
        immediate: yes
        permanent: yes
      with_items: "{{ ip_servere }}"
      when: ansible_distribution in os_se


    - name: Drop ssh from the public zone
      firewalld:
        zone: public
        service: ssh
        state: disabled
        immediate: yes
        permanent: yes

######################  Port changed of SSH  ##################################

    - name: Change SSH port number.
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^Port"
        line: "Port 2222"
        #notify: "Restart sshd"
        
######################  Define Listen Adress #################################

    - name: Define ListenAddress.
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^ListenAddress"
        line: "ListenAddress 10.0.0.2"

#####################  Define Protocol version  ############################

    - name: Define Protocol version.
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^Protocol"
        line: "Protocol 2"

####################  Selinux for new port  ###############################

    - name: Setup Selinux for SSH Port.
      seport:
        ports: "2222"
        proto: "tcp"
        setype: "ssh_port_t"
        state: "present"
      when: ansible_distribution in os_rest

###################  Copy SSH Key to node  ################################

    - name: Copy SSH key.
      authorized_key:
        user: student
        state: present
        manage_dir: yes
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

##################   PA & PRL change to NO  #############################

    - name: Prohibit PasswordAuthentication in SSH config file.
      replace:
        path: /etc/ssh/sshd_config
        regexp: "PasswordAuthentication yes"
        replace: "PasswordAuthentication no"
    - name: Prohibit PermitRootLogin in SSH Config file.
      replace:
        path: /etc/ssh/sshd_config
        regexp: "PermitRootLogin yes"
        replace: "PermitRootLogin no"
    - name: PasswordAuthentication change in SSH Config file.
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^PasswordAuthentication yes"
        line: "PasswordAuthentication no"

#####################  Restart Services  ###############################

    - name: Restart SSHD Service.
      service:
        name: sshd
        state: started

####################  Remove packages  #################################

    - name: Removing FTP
      yum:
        name: ftp
        state: absent
    - name: Removing TELNET
      yum:
        name: telnet
        state: absent
    - name: Remove undesirable packages
      package:
        name: "{{ unnecessary_software }}"
        state: absent

##################  Disable unsed services  #############################

    - name: Stop and disable unnecessary services
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items: "{{ unnecessary_services }}"
      ignore_errors: yes

################   Booting message   ###########################
    - name: Set a message of the day
      copy:
        dest: /etc/motd
        src: /etc/motd
        owner: root
        group: root
        mode: 0644

##################   Login Message   ###########################

    - name: Set a login banner
      copy:
        dest: "{{ item }}"
        src: /etc/issue
        owner: root
        group: root
        mode: 0644
      with_items:
        - /etc/issue
        - /etc/issue.net

######################    HANDLERS  #############################


  handlers:
    - name: Reload SSH
      service:
        name: sshd
        state: reloaded
    - name: Reload ftp
      service:
        name: ftp
        state: reloaded
    - name: Reload telnet
      service:
        name: telnet
        state: reloaded

...
